package sopsyaml

import (
	"testing"

	"github.com/Kreibich04/sops-config/internal/merge"
)

func TestRenderGoldenOutput(t *testing.T) {
	rules := []merge.ResolvedRule{
		{
			PathRegex:      "^muc/secrets/.*",
			EncryptedRegex: "^(data|stringData)$",
			Comment:        "MUC secrets directory",
			PGP:            []string{"AABB11"},
			Age:            []string{"AABB11"},
		},
		{
			PathRegex:      "^fra/secure-secrets/.*",
			EncryptedRegex: "^(data|stringData)$",
			PGP:            []string{"BBCC11", "CCBB11"},
		},
	}

	got, err := Render(rules)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := `# Code generated by sops-config generate. DO NOT EDIT.
# Regenerate with: sops-config generate
creation_rules:
  - path_regex: ^muc/secrets/.*
    encrypted_regex: ^(data|stringData)$
    comment: MUC secrets directory
    pgp: AABB11
    age: AABB11
  - path_regex: ^fra/secure-secrets/.*
    encrypted_regex: ^(data|stringData)$
    pgp: BBCC11,CCBB11
`
	if string(got) != want {
		t.Fatalf("output mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}
