package sopsyaml

import (
	"bytes"
	"os"
	"strings"

	"github.com/Kreibich04/sops-config/internal/merge"
	"gopkg.in/yaml.v3"
)

const header = "# Code generated by sops-config generate. DO NOT EDIT.\n" +
	"# Regenerate with: sops-config generate\n"

// Render marshals resolved rules into .sops.yaml bytes, preceded by a fixed
// (timestamp-free) generated-file header so repeated runs over unchanged
// input produce byte-identical output.
func Render(rules []merge.ResolvedRule) ([]byte, error) {
	file := sopsFile{CreationRules: make([]creationRule, 0, len(rules))}
	for _, r := range rules {
		file.CreationRules = append(file.CreationRules, creationRule{
			PathRegex:      r.PathRegex,
			EncryptedRegex: r.EncryptedRegex,
			Comment:        r.Comment,
			PGP:            strings.Join(r.PGP, ","),
			Age:            strings.Join(r.Age, ","),
		})
	}

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(file); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}

	out := make([]byte, 0, len(header)+buf.Len())
	out = append(out, header...)
	out = append(out, buf.Bytes()...)
	return out, nil
}

// WriteFile renders the rules and writes them to path.
func WriteFile(path string, rules []merge.ResolvedRule) error {
	data, err := Render(rules)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
